[package]
name = "xon"
version = "0.2.0"
description = "x-on — 极速启动器"
authors = ["x-on"]
edition = "2021"

[lib]
name = "x_on_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-autostart = "2"
notify = "6"
json5 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
lnk = "0.6"
image = { version = "0.25", default-features = false, features = ["png"] }
base64 = "0.22"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
